### ISSUE TITLE
layerindex needs LAYERDEPENDS or LAYERRECOMMENDS

### ISSUE THREAD

**Issue by moto-timo** [jwinarske/meta-vulkan#17]
You need a LAYERDEPENDS or LAYERRECOMMENDS on meta-qt5 (and probably also meta-clang):

```
layers@updatelayers:/opt/layerindex$ ./layerindex/update.py --layer meta-vulkan --dry-run
INFO: Fetching remote repository https://github.com/jwinarske/meta-vulkan
INFO: Fetching remote repository git://git.openembedded.org/openembedded-core
INFO: Fetching remote repository git://git.openembedded.org/bitbake
INFO: Collecting data for layer meta-vulkan on branch master (kirkstone)
NOTE: Starting bitbake server...
BBFILE_COLLECTIONS = "meta-vulkan"
LAYERVERSION = ""
LAYERDEPENDS = ""
LAYERRECOMMENDS = ""
INFO: Collecting data for layer meta-vulkan on branch master (kirkstone)
NOTE: Starting bitbake server...
ERROR: Unable to read /opt/workdir/https___github_com_jwinarske_meta-vulkan/dynamic-layers/qt5-layer/recipes-graphics/vulkan-caps-viewer/vulkan-caps-viewer_git.bb: Traceback (most recent call last):
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 90, in runCommand
    result = command_method(self, commandline)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/command.py", line 577, in parseRecipeFile
    envdata = command.cooker.databuilder._parse_recipe(config_data, fn, appendfiles, mc, layername)[cls]
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/cookerdata.py", line 507, in _parse_recipe
    return bb.parse.handle(bbfile, bb_data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/__init__.py", line 115, in handle
    return h['handle'](fn, data, include, baseconfig)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/parse_py/BBHandler.py", line 140, in handle
    statements.eval(d)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 20, in eval
    statement.eval(data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/ast.py", line 315, in eval
    bb.parse.BBHandler.inherit(self.classes, self.filename, self.lineno, data)
  File "/opt/workdir/git___git_openembedded_org_bitbake/lib/bb/parse/parse_py/BBHandler.py", line 70, in inherit
    raise ParseError("Could not inherit file %s" % (file), fn, lineno)
bb.parse.ParseError: ParseError at /opt/workdir/https___github_com_jwinarske_meta-vulkan/dynamic-layers/qt5-layer/recipes-graphics/vulkan-caps-viewer/vulkan-caps-viewer_git.bb:28: Could not inherit file classes/qmake5.bbclass
```

**Comment by jwinarske** [comment]
@moto-timo Hi Tim,

Thanks for the report.  See if it passes now.  I tried to setup [layerindex-web](https://github.com/yoctoproject/layerindex-web) on my Fedora machine, which only runs rootless podman; no luck just yet so not able to confirm.

**Comment by moto-timo** [comment]
@jwinarske rootless podman is on "The List". We're tightly coupled to docker and docker-compose at the moment, as you know.

**Comment by moto-timo** [comment]
@jwinarske looks good, Thank you very much. https://layers.openembedded.org/layerindex/branch/kirkstone/layer/meta-vulkan/

**Comment by moto-timo** [comment]
> @jwinarske rootless podman is on "The List". We're tightly coupled to docker and docker-compose at the moment, as you know.

@jwinarske feel free to file an [enhancement request for podman support](https://bugzilla.yoctoproject.org/enter_bug.cgi?product=Layer%20Index) for [layerindex-web](https://git.yoctoproject.org/layerindex-web).
